create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
create table food (price float(53) not null, id_food uuid not null, description varchar(255), type varchar(255), primary key (id_food));
create table tb_products (value numeric(38,2), id_product uuid not null, description varchar(255), name varchar(255), primary key (id_product));
create table users (role smallint check (role between 0 and 1), id uuid not null, login varchar(255), password varchar(255), primary key (id));
